In [2]:

import numpy as np

#so there are two methods we can convert normal array to numpy array or create new numpy array

#first method 
arr1 = np.array([1,2,3])

#second method 
arr2 = [2,3,4]
arr2 = np.array(arr2)
#lets check 
print(arr2+arr1)

print(f"\n Array Dimensions \n")

#lets create 1D 2D 3D arrays
#1D
print("1D Array")
arr1d = np.array([1,2,3])
print(f"1D array Dimension: {arr1d.ndim}")
print(f"1D array Shape: {arr1d.shape}")
print(f"Printing its data type {arr1d.dtype}")
print(f"1D array strides new concept {arr1d.strides}") #New concept PENDING
print(arr1d)
print(f"its Address {arr1d.data}")

print(f"\n2D Array")
#2D array
#rows #column
arr2d = np.ones((2,2))
print(f"2D array Dimension: {arr2d.ndim}")
print(f"2D array Shape: {arr2d.shape}")
print(f"2D array strides: {arr2d.strides}")  #new
print(arr2d)

print(f"\n 3D array\n")

#lets create by ourself
arr3d = np.array([[[1,2,3],
                  [4,5,6]],
                  
                  [[7,8,9],
                   [10,11,12]]])     #_ row column
print(arr3d) 
#lets print perticular element 
print(f"\nprinting perticular element")
print(arr3d[1,0,2]) #it will print 9
print(f"3D array dimension: {arr3d.ndim}")
print(f"3D array shape: {arr3d.shape}")
print(f"3D array strides: {arr3d.strides}")

# we leaned 1D 2D and 3D array


[3 5 7]

 Array Dimensions 

1D Array
1D array Dimension: 1
1D array Shape: (3,)
Printing its data type int64
1D array strides new concept (8,)
[1 2 3]
its Address <memory at 0x000001C27177BE80>

2D Array
2D array Dimension: 2
2D array Shape: (2, 2)
2D array strides: (16, 8)
[[1. 1.]
 [1. 1.]]

 3D array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

printing perticular element
9
3D array dimension: 3
3D array shape: (2, 2, 3)
3D array strides: (48, 24, 8)


In [3]:
#lets learn math inbuild functions 
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"The mean of given array is: {np.mean(arr)}")
print(f"The median (middle) value of given array is: {np.median(arr)}")
print(f"The standard deviation of given array is; {np.std(arr).round(3)}")
print(f"This are all mathematical operations")

The mean of given array is: 5.5
The median (middle) value of given array is: 5.5
The standard deviation of given array is; 2.872
This are all mathematical operations


In [4]:
#lets Learn rephaping of array
#suppose we have 2D array we will convert it into 1D
arr2D = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr2D)
#lets convert to 1D
a=arr2D.reshape(-1)  #-1 converts multidimensional array to 1D 
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [5]:
arr = np.random.rand(2,3).round(2)
print(arr)

[[0.38 0.4  0.07]
 [0.06 0.33 0.22]]


In [6]:
arr1=np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.vstack((arr1,arr2)) #vertical Stacking
print(arr3)

[[1 2 3]
 [4 5 6]]


In [7]:
arr1=np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.hstack((arr1,arr2)) #Horizontal Stacking
print(arr3)

[1 2 3 4 5 6]


In [8]:
arr = np.array([9,3,4,-2,0,0,4,1])
arr=np.sort(arr)
print(arr)

[-2  0  0  1  3  4  4  9]


In [9]:
#lets learn Identity Matrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
arr=np.array([[1,2,3],
              [4,5,6]])
arrT=np.transpose(arr) #transpose
print(arrT)  #so rows become column and column becom rows 

[[1 4]
 [2 5]
 [3 6]]


In [11]:
arr = np.arange(1,10,1) #last number is not included
print(arr)

[1 2 3 4 5 6 7 8 9]


In [12]:
arr = np.linspace(1,10,20) # last number is included
print(arr)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


FROM LAB NOTES

In [24]:
#Array Creation Method
arr=np.zeros((2,3))
print(arr)
arr=np.ones((2,3))
print(f"\n{arr}")
arr=np.full((2,3),3)
print(f"\n{arr}")
arr = np.eye(4) #so we created ientity matrix 4x4
print(f"\n{arr}")

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[3 3 3]
 [3 3 3]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.arange(1,10,2) # here 10 in not included
print(f"we are printing 1-10 with 2s gap: {arr}")

we are printing 1-10 with 2s gap: [1 2 3 4 5 6 7 8 9]


In [31]:
arr=np.linspace(1,5,10)
print(f"We are printing 10 no between 1 and 5: \n{arr}")#here 5 is incluuded

We are printing 10 no between 1 and 5: 
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [34]:
arr = np.random.rand(2,3)
print(arr)
arr = np.random.randint(1, 1000, size=(3, 3))
print(f"\n{arr}")

[[0.02020944 0.86901875 0.65119123]
 [0.25000166 0.299117   0.33754892]]

[[244  95  26]
 [657 831 245]
 [901  42 528]]


In [ ]:
arr = np.array([[1,2,3],[1,2,3]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.reshape(-1)) #this is same at flattern()
print(arr.dtype)
arr=np.array([[1,2],
              [4,5]])
print(arr.transpose())
arr = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr,arr2))
print(f"\n{arr}")



(2, 3)
2
6
[1 2 3 1 2 3]
int64
[[1 4]
 [2 5]]

[1 2 3 4 5 6]


In [60]:
arr1=np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.vstack((arr1,arr2)) #vertical Stacking
print(arr3)

[[1 2 3]
 [4 5 6]]


In [61]:
arr1=np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.hstack((arr1,arr2)) #horizontal Stacking
print(arr3)

[1 2 3 4 5 6]


In [63]:
x = np.array([22,33,44,55])
y = np.array([4,3,2,1])

print(x + y)
print(x - y)
print(x ** 2)
print(x * y)
print(x / y)

[26 36 46 56]
[18 30 42 54]
[ 484 1089 1936 3025]
[88 99 88 55]
[ 5.5 11.  22.  55. ]


In [65]:
arr = np.array([33,33,22,104,33,90,45,33])

print(arr[0])
print(arr[-1])
print(arr[1:6])
print(arr[::1])
print(arr[::-1])

33
33
[ 33  22 104  33  90]
[ 33  33  22 104  33  90  45  33]
[ 33  45  90  33 104  22  33  33]


In [69]:
arr = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(arr[2, 2]) # the last elemenet will prinyt
print(arr[2, :])
print(arr[:, 2])
print(arr[0:1, 1:3])

9
[7 8 9]
[3 6 9]
[[2 3]]
